["East","OPF_F","Infantry","OIA_InfSquad"] call d_fnc_GetConfigGroup,
["East","OPF_F","Infantry","OIA_InfSquad_Weapons"] call d_fnc_GetConfigGroup,
["East","OPF_F","Infantry","OIA_InfTeam"] call d_fnc_GetConfigGroup,
["East","OPF_F","Infantry","OIA_InfTeam_AT"] call d_fnc_GetConfigGroup,
["East","OPF_F","Infantry","OI_reconPatrol"] call d_fnc_GetConfigGroup,
["East","OPF_F","Infantry","OI_reconTeam"] call d_fnc_GetConfigGroup,
["East","OPF_F","UInfantry","OIA_GuardSquad"] call d_fnc_GetConfigGroup,
["East","OPF_F","UInfantry","OIA_GuardTeam"] call d_fnc_GetConfigGroup,
["East","OPF_F","Infantry","OIA_InfTeam_AA"] call d_fnc_GetConfigGroup