["I_MBT_03_cannon_F"],
["I_APC_tracked_03_cannon_F","I_LT_01_AT_F","I_LT_01_cannon_F"],
["I_APC_Wheeled_03_cannon_F"],
["I_LT_01_AA_F"],
["I_G_Offroad_01_armed_F","I_G_Offroad_01_AT_F","I_C_Offroad_02_AT_F"],
["I_MRAP_03_gmg_F","I_LT_01_scout_F"],
["I_HMG_01_F","I_GMG_01_high_F"],
["I_GMG_01_F","I_HMG_01_high_F","I_static_AA_F","I_static_AT_F"],
["I_Mortar_01_F", "I_G_Mortar_01_F"],
["I_Truck_02_fuel_F"],
["I_Truck_02_box_F"],
["I_Truck_02_ammo_F"]