["West","BLU_F","Infantry","BUS_InfSquad"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_InfSquad_Weapons"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_InfTeam"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_InfTeam_AT"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_InfSentry"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_ReconPatrol"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_ReconSentry"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_ReconTeam"] call d_fnc_GetConfigGroup,
["West","BLU_F","Infantry","BUS_InfTeam_AA"] call d_fnc_GetConfigGroup