["PRACS_SLA_T72B","PRACS_SLA_T72BV","PRACS_SLA_T80U"],
["PRACS_SLA_BMP1","PRACS_SLA_BMP2","PRACS_SLA_BTR80A","PRACS_SLA_BMD1","PRACS_SLA_BMD2"],
["PRACS_SLA_BRDM","PRACS_SLA_BRDM_ATGM","PRACS_SLA_MTLB","PRACS_SLA_BTR60","PRACS_SLA_BTR80"],
["PRACS_SLA_ZSU23","PRACS_SLA_MTLB_ZU23","PRACS_SLA_URAL_Zu23","PRACS_SLA_SA8"], //"PRACS_SLA_2S6M_Tunguska","PRACS_SLA_SA6","PRACS_SLA_SA13","PRACS_SLA_SA9","PRACS_SLA_SA17"
["PRACS_SLA_Type63","PRACS_SLA_UAZ_DSHKM","PRACS_SLA_UAZ_DSHKM_paratrooper"],
["PRACS_SLA_UAZ_AGS","PRACS_SLA_UAZ_SPG9","PRACS_SLA_BTR40_mortar"], //"PRACS_SLA_BTR40_AAM",
["PRACS_SLA_DShK","PRACS_SLA_DSHk_Mini"],
["PRACS_SLA_AGS30_tripod","PRACS_SLA_SPG9_tripod","PRACS_SLA_SPG9M_tripod","PRACS_SLA_9k115"],
["PRACS_SLA_M46","PRACS_SLA_D30","PRACS_SLA_S60","PRACS_SLA_ZPU4","PRACS_SLA_ZU23","PRACS_SLA_2B14"], //"PRACS_SLA_Sa2"
["PRACS_SLA_URAL_Fuel"],
["PRACS_SLA_URAL_Repair"],
["PRACS_SLA_MAZ_ammo","PRACS_SLA_Ural_Ammo"]