["SPE_PzKpfwIII_J","SPE_PzKpfwIII_L","SPE_PzKpfwIII_M","SPE_PzKpfwIII_N","SPE_PzKpfwIV_G","SPE_PzKpfwVI_H1","SPE_Nashorn"],
["SPE_SdKfz250_1"],
["SPE_ST_SdKfz250_1"],
["SPE_ST_OpelBlitz_Flak38", "SPE_FlaK_36_AA","SPE_ST_FlaK_36_AA"],
["SPE_SdKfz250_1","SPE_ST_SdKfz250_1"],
["SPE_SdKfz250_1","SPE_ST_SdKfz250_1"],
["SPE_MG34_Lafette_Deployed","SPE_MG42_Lafette_Deployed","SPE_MG34_Lafette_low_Deployed"],
["SPE_FlaK_36","SPE_FlaK_38","SPE_Pak40"],
["SPE_GrW278_1"],
["SPE_OpelBlitz_Fuel"],
["SPE_OpelBlitz_Repair"],
["SPE_OpelBlitz_Ammo"]
