["B_MBT_01_cannon_F","B_MBT_01_TUSK_F"],
["B_APC_Tracked_01_rcws_F"],
["B_APC_Wheeled_01_cannon_F","B_AFV_Wheeled_01_cannon_F","B_AFV_Wheeled_01_up_cannon_F"],
["B_APC_Tracked_01_AA_F"],
["B_LSV_01_armed_F","B_MRAP_01_hmg_F","B_G_Offroad_01_armed_F"],
["B_LSV_01_AT_F","B_MRAP_01_gmg_F","B_G_Offroad_01_AT_F"],
["B_HMG_01_F","B_HMG_01_high_F","B_HMG_01_A_F"],
["B_GMG_01_F","B_GMG_01_high_F","B_GMG_01_A_F","B_static_AT_F","B_static_AA_F"],
["B_Mortar_01_F", "B_G_Mortar_01_F"],
["B_Truck_01_fuel_F"],
["B_Truck_01_Repair_F"],
["B_Truck_01_ammo_F"],
["B_UAV_01_F","B_UAV_06_F","B_UGV_01_rcws_F"]
