d_mt_bonus_vehicle_array =
switch (d_own_side) do {
	case "GUER": {
		["PRACS_M1165_M2","PRACS_M1165_Mk19","PRACS_M1165_M134_QSB",
		"PRACS_M113_M2","PRACS_M113_mk19","PRACS_BMR_A3_M2","PRACS_BMR_A3_Mk19",
		"PRACS_BMR_A3_M3_SFOD","PRACS_BMR_A3_GA1","PRACS_VEC_M242","PRACS_M1117",
		"PRACS_m48_chapparal","PRACS_M163_VADS",
		"PRACS_Sa330_Puma_AS"]
	};
	case "WEST": {
		["CUP_B_Jackal2_GMG_GB_W","CUP_B_LR_MG_GB_W","CUP_I_UAZ_AGS30_UN","CUP_I_UAZ_MG_UN","CUP_I_UAZ_SPG9_UN","CUP_I_M113_UN","CUP_I_BRDM2_UN","CUP_B_HMMWV_Avenger_USA","CUP_B_HMMWV_Crows_M2_USA",
		"CUP_B_HMMWV_M2_GPK_USA","CUP_B_HMMWV_SOV_USA","CUP_B_HMMWV_TOW_USA","CUP_B_M113_USA","CUP_B_AAV_USMC","CUP_B_LAV25_USMC"]
	};
	case "EAST": {["O_MRAP_02_hmg_F","O_MRAP_02_gmg_F"]};
};
