//Land_Shop_Town_03_F
isNil{params["_b"];_f=[];_dir=getDir _b;
_box1=createSimpleObject["a3\structures_f_epa\mil\scrapyard\paperbox_closed_f.p3d",[0,0,0]];
_box2=createSimpleObject["a3\structures_f_epa\mil\scrapyard\paperbox_closed_f.p3d",[0,0,0]];
_cashD=createSimpleObject["A3\Structures_F\Furniture\CashDesk_F.p3d",[0,0,0]];
_rack1=createSimpleObject["a3\structures_f\furniture\Rack_F.p3d",[0,0,0]];
_rack2=createSimpleObject["a3\structures_f\furniture\Rack_F.p3d",[0,0,0]];
_rack3=createSimpleObject["A3\Structures_F\Training\Shoot_House_Wall_Long_F.p3d",[0,0,0]];
_shelf1=createSimpleObject["A3\Structures_F\Furniture\Metal_rack_F.p3d",[0,0,0]];
_shelf2=createSimpleObject["A3\Structures_F\Furniture\Metal_rack_F.p3d",[0,0,0]];
_shelf3=createSimpleObject["A3\Structures_F\Furniture\Metal_rack_F.p3d",[0,0,0]];
_cro=createSimpleObject["a3\Props_F_Orange\Items\Tools\Crowbar_01_F.p3d",[0,0,0]];
_pliers=createSimpleObject["a3\structures_f\Items\Tools\Pliers_F.p3d",[0,0,0]];
_rake=createSimpleObject["a3\weapons_f\mines\rake.p3d",[0,0,0]];
_saw=createSimpleObject["a3\structures_f\Items\Tools\Saw_F.p3d",[0,0,0]];
_screwD=createSimpleObject["a3\structures_f\Items\Tools\Screwdriver_V1_F.p3d",[0,0,0]];
_shelf=createSimpleObject["a3\structures_f\furniture\ShelvesMetal_F.p3d",[0,0,0]];
_shovel=createSimpleObject["a3\structures_f_epa\Items\Tools\Shovel_F.p3d",[0,0,0]];
_hammer=createSimpleObject["a3\structures_f\Items\Tools\Hammer_F.p3d",[0,0,0]];
_cashD=createSimpleObject["A3\Structures_F\Furniture\CashDesk_F.p3d",[0,0,0]];
_rack1=createSimpleObject["a3\structures_f\furniture\Rack_F.p3d",[0,0,0]];
_rack2=createSimpleObject["a3\structures_f\furniture\Rack_F.p3d",[0,0,0]];
_rack3=createSimpleObject["A3\Structures_F\Training\Shoot_House_Wall_Long_F.p3d",[0,0,0]];
_rake1=createSimpleObject["a3\weapons_f\mines\rake.p3d",[0,0,0]];
_rake2=createSimpleObject["a3\weapons_f\mines\rake.p3d",[0,0,0]];
_rake3=createSimpleObject["a3\weapons_f\mines\rake.p3d",[0,0,0]];
_shelf1=createSimpleObject["A3\Structures_F\Furniture\Metal_rack_F.p3d",[0,0,0]];
_shelf2=createSimpleObject["A3\Structures_F\Furniture\Metal_rack_F.p3d",[0,0,0]];
_shelf3=createSimpleObject["A3\Structures_F\Furniture\Metal_rack_F.p3d",[0,0,0]];
_shelf4=createSimpleObject["A3\Structures_F\Furniture\ShelvesMetal_F.p3d",[0,0,0]];
_shelf5=createSimpleObject["A3\Structures_F\Furniture\ShelvesMetal_F.p3d",[0,0,0]];
_shelf6=createSimpleObject["A3\Structures_F\Furniture\ShelvesMetal_F.p3d",[0,0,0]];
_shovel1=createSimpleObject["a3\structures_f_epa\Items\Tools\Shovel_F.p3d",[0,0,0]];
_shovel2=createSimpleObject["a3\structures_f_epa\Items\Tools\Shovel_F.p3d",[0,0,0]];
_shovel3=createSimpleObject["a3\structures_f_epa\Items\Tools\Shovel_F.p3d",[0,0,0]];
_cro1=createSimpleObject["a3\Props_F_Orange\Items\Tools\Crowbar_01_F.p3d",[0,0,0]];
_cro2=createSimpleObject["a3\Props_F_Orange\Items\Tools\Crowbar_01_F.p3d",[0,0,0]];
_cro3=createSimpleObject["a3\Props_F_Orange\Items\Tools\Crowbar_01_F.p3d",[0,0,0]];
_saw1=createSimpleObject["a3\structures_f\Items\Tools\Saw_F.p3d",[0,0,0]];
_saw2=createSimpleObject["a3\structures_f\Items\Tools\Saw_F.p3d",[0,0,0]];
_saw3=createSimpleObject["a3\structures_f\Items\Tools\Saw_F.p3d",[0,0,0]];
_screwD1=createSimpleObject["a3\structures_f\Items\Tools\Screwdriver_V1_F.p3d",[0,0,0]];
_screwD2=createSimpleObject["a3\structures_f\Items\Tools\Screwdriver_V1_F.p3d",[0,0,0]];
_screwD3=createSimpleObject["a3\structures_f\Items\Tools\Screwdriver_V1_F.p3d",[0,0,0]];
_ham1=createSimpleObject["a3\structures_f\Items\Tools\Hammer_F.p3d",[0,0,0]];
_ham2=createSimpleObject["a3\structures_f\Items\Tools\Hammer_F.p3d",[0,0,0]];
_ham3=createSimpleObject["a3\structures_f\Items\Tools\Hammer_F.p3d",[0,0,0]];
_bucket1=createSimpleObject["a3\props_f_orange\humanitarian\supplies\plasticbucket_01_f.p3d",[0,0,0]];
_bucket2=createSimpleObject["a3\props_f_orange\humanitarian\supplies\plasticbucket_01_f.p3d",[0,0,0]];
_tape1=createSimpleObject["A3\Structures_F\Items\Tools\Meter3m_F.p3d",[0,0,0]];
_tape2=createSimpleObject["A3\Structures_F\Items\Tools\Meter3m_F.p3d",[0,0,0]];
_tape3=createSimpleObject["A3\Structures_F\Items\Tools\Meter3m_F.p3d",[0,0,0]];
_trolly=createSimpleObject["a3\structures_f_heli\civ\market\pallettrolley_01_yellow_f.p3d",[0,0,0]];
{_f pushBack _x}forEach[_box1,_box2,_bucket1,_bucket2,_cashD,_cro1,_cro2,_cro3,_hammer1,_hammer2,_hammer3,_rack1,_rack2,_rack3,_rake1,_rake2,_saw1,_saw2,_saw3,_shelf1,_shelf2,_shelf3,_shelf4,_shelf5,_shelf6,_tape1,_tape2,_tape3,_trolly];
_b setVariable["PF",_f];

_cashD setPos(_b modelToWorld[-3.648,-5.645,-3.37]);
_rack1 setPos(_b modelToWorld[-1.38,-5.78,-1.7]);
_rack2 setPos(_b modelToWorld[-1.38,-4.39,-1.7]);
_rack3 setPos(_b modelToWorld[-6.69,-4.5,.9]);
_shelf1 setPos(_b modelToWorld[-6.45,-4.863,-2.4]);
_shelf2 setPos(_b modelToWorld[-6.45,-5.923,-2.4]);
_shelf3 setPos(_b modelToWorld[-6.45,-3.8,-2.4]);
_cro1 setPos(_b modelToWorld[-6.59,-6,-.76]);
_cro2 setPos(_b modelToWorld[-6.55,-6,-.76]);
_cro3 setPos(_b modelToWorld[-6.51,-6,-.76]);
_saw1 setPos(_b modelToWorld[-6.59,-6,-1.6]);
_saw2 setPos(_b modelToWorld[-6.55,-6,-1.6]);
_saw3 setPos(_b modelToWorld[-6.51,-6,-1.6]);
_shovel1 setPos(_b modelToWorld[-6.58,-3.5,-1.8]);
_shovel2 setPos(_b modelToWorld[-6.53,-3.5,-1.8]);
_shovel3 setPos(_b modelToWorld[-6.48,-3.5,-1.8]);
_rake1 setPos(_b modelToWorld[-6.61,-4,-.4]);
_rake2 setPos(_b modelToWorld[-6.53,-4,-.4]);
_ham1 setPos(_b modelToWorld[-6.59,-5.5,-1.6]);
_ham2 setPos(_b modelToWorld[-6.53,-5.5,-1.6]);
_ham3 setPos(_b modelToWorld[-6.47,-5.5,-1.6]);
_shelf4 setPos(_b modelToWorld[-5.6,.8,-3.4]);
_shelf5 setPos(_b modelToWorld[-3.61,.801,-3.4]);
_trolly setPos(_b modelToWorld[3.2,-.4,-2.272]);
_box1 setPos(_b modelToWorld[3.2,.07,-2.1]);
_box2 setPos(_b modelToWorld[3.2,.0692,-.9038]);
{_x setDir _dir}forEach[_rack1,_rack2,_cro1,_cro2,_cro3,_saw1,_saw2,_saw3,_shovel1,_shovel2,_shovel3,_rake1,_rake2,_ham1,_ham2,_ham3];
{_x setDir(_dir-90)}forEach[_cashD,_rack3,_shelf1,_shelf2,_shelf3,_shelf4,_shelf5,_trolly,_box1,_box2];
{_x setVectorDirAndUp[[0,0,1],[-1,0,0]]}forEach[_cro1,_cro2,_cro3,_saw1,_saw2,_saw3];
{_x setVectorDirAndUp[[0,0,1],[1,10,0]]}forEach[_ham1,_ham2,_ham3];
{_x setVectorDirAndUp[[0,0,-1],[-1,0,0]]}forEach[_shovel1,_shovel2,_shovel3];
_rake1 setVectorDirAndUp[[0,0,1],[1,0,0]];
_rake2 setVectorDirAndUp[[0,0,1],[1,0,0]]}