//Land_House_1W11_F
isNil{params["_b"];_f=[];_dir=getDir _b;
_book=createSimpleObject["a3\Structures_F_Enoch\Furniture\Cases\library_a\library_a.p3d",[0,0,0]];
_chair=createSimpleObject["a3\structures_f\furniture\chairwood_f.p3d",[0,0,0]];
_chair2=createSimpleObject["a3\structures_f\furniture\chairwood_f.p3d",[0,0,0]];
_chair3=createSimpleObject["a3\structures_f\furniture\chairwood_f.p3d",[0,0,0]];
_chair4=createSimpleObject["a3\structures_f\furniture\chairwood_f.p3d",[0,0,0]];
_cook=createSimpleObject["a3\structures_f_epa\items\tools\butanecanister_f.p3d",[0,0,0]];
_cook2=createSimpleObject["a3\structures_f_epa\items\tools\butanecanister_f.p3d",[0,0,0]];
_cook3=createSimpleObject["a3\structures_f_epa\items\tools\butanecanister_f.p3d",[0,0,0]];
_cook4=createSimpleObject["a3\structures_f_epa\items\tools\butanecanister_f.p3d",[0,0,0]];
_desk=createSimpleObject["a3\structures_f\furniture\tabledesk_f.p3d",[0,0,0]];
_desk2=createSimpleObject["a3\structures_f\furniture\tabledesk_f.p3d",[0,0,0]];
_desk3=createSimpleObject["a3\structures_f\furniture\tabledesk_f.p3d",[0,0,0]];
_fridge=createSimpleObject["a3\structures_f_heli\items\electronics\fridge_01_f.p3d",[0,0,0]];
_heat=createSimpleObject["a3\Structures_F_Enoch\Furniture\kitchen\Dkamna_uhli\Dkamna_uhli.p3d",[0,0,0]];
_oven=createSimpleObject["a3\structures_f_heli\items\luggage\metalcase_01_medium_f.p3d",[0,0,0]];
_oven2=createSimpleObject["a3\structures_f_heli\items\luggage\metalcase_01_medium_f.p3d",[0,0,0]];
_oven3=createSimpleObject["a3\structures_f_heli\items\electronics\pcset_01_screen_f.p3d",[0,0,0]];
_mw=createSimpleObject["a3\structures_f_heli\items\electronics\microwave_01_f.p3d",[0,0,0]];
_pic=createSimpleObject[selectRandom["a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_a\picture_a.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_a_02\picture_a_02.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_a_03\picture_a_03.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_a_04\picture_a_04.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_a_05\picture_a_05.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_b\picture_b.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_b_02\picture_b_02.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_c\picture_c.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_c_02\picture_c_02.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_d\picture_d.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_d_02\picture_d_02.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_e\picture_e.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_e_02\picture_e_02.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_f\picture_f.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_f_02\picture_f_02.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_g\picture_g.p3d","a3\Structures_F_Enoch\Furniture\Decoration\WallBoards\picture_g_02\picture_g_02.p3d"],[0,0,0]];
_sink=createSimpleObject["a3\Structures_F_Enoch\Furniture\School_equipment\lab_sink.p3d",[0,0,0]];
_table=createSimpleObject["a3\structures_f_epa\civ\camping\woodentable_small_f.p3d",[0,0,0]];
_table2=createSimpleObject["a3\structures_f_epa\civ\camping\woodentable_small_f.p3d",[0,0,0]];
{_f pushBack _x}forEach[_book,_chair,_chair2,_chair3,_chair4,_cook,_cook2,_cook3,_cook4,_desk,_desk2,_desk3,_fridge,_heat,_oven,_oven2,_oven3,_mw,_pic,_sink,_table,_table2];_b setVariable["PF",_f];

_book setPos(_b modelToWorld[-5.06,-.62,-2.9]);
_chair setPos(_b modelToWorld[1.8,-0.95,-2.65]);
_chair2 setPos(_b modelToWorld[1,-0.95,-2.65]);
_chair3 setPos(_b modelToWorld[0.5,-3,-2.65]);_chair3 setDir(_dir+70);
_chair4 setPos(_b modelToWorld[-.4,-3,-2.65]);
_cook setPos(_b modelToWorld[-2.7,-.38,-1.94]);
_cook2 setPos(_b modelToWorld[-2.7,-.68,-1.94]);
_cook3 setPos(_b modelToWorld[-3.1,-.38,-1.94]);
_cook4 setPos(_b modelToWorld[-3.1,-.68,-1.94]);
_desk setPos(_b modelToWorld[-4.15,-.62,-1.9]);
_fridge setPos(_b modelToWorld[-4.3,-2.5,-1.62]);
_heat setPos(_b modelToWorld[-4.3,-3,-2.64]);
_oven setPos(_b modelToWorld[-2.89,-.53,-1.93]);
_oven2 setPos(_b modelToWorld[-2.89,-.53,-2.3]);
_oven3 setPos(_b modelToWorld[-2.89,-.7802,-2.151]);
_mw setPos(_b modelToWorld[-4.2,-.5,-1.72]);_mw setDir(_dir-30);
_pic setPos(_b modelToWorld[1.4,-0.25,-2.5]);_pic setDir(_dir+180);
_sink setPos(_b modelToWorld[-2.1,-.7,-2.6312]);_sink setDir(_dir+180);
_table setPos(_b modelToWorld[1.4,-0.96,-1.79]);
_table2 setPos(_b modelToWorld[0,-3,-1.79]);
{_x setDir _dir}forEach[_desk,_oven3,_table,_table2];
{_x setDir(_dir+90)}forEach[_chair,_oven,_oven2];
{_x setDir(_dir+270)}forEach[_book,_chair2,_chair4,_fridge,_heat]}
