//Land_House_1W11_F
isNil{params["_b"];_f=[];_dir=getDir _b;
_book=createSimpleObject["a3\Structures_F_Enoch\Furniture\Cases\library_a\library_a.p3d",[0,0,0]];
_box=createSimpleObject["a3\props_f_orange\humanitarian\supplies\paperbox_01_small_ransacked_f.p3d",[0,0,0]];
_box2=createSimpleObject["a3\props_f_orange\humanitarian\supplies\paperbox_01_small_destroyed_f.p3d",[0,0,0]];
_chair=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_chair2=createSimpleObject["a3\structures_f_heli\furniture\officechair_01_f.p3d",[0,0,0]];
_desk=createSimpleObject["a3\Structures_F_Enoch\Furniture\Tables\conference_table_a\conference_table_a.p3d",[0,0,0]];
_desk2=createSimpleObject["a3\Structures_F_Enoch\Furniture\Various\workbench_DZ.p3d",[0,0,0]];
_junk=createSimpleObject["a3\props_f_exp\civilian\garbage\garbageheap_03_f.p3d",[0,0,0]]; 
_junk2=createSimpleObject["a3\props_f_exp\civilian\garbage\garbageheap_03_f.p3d",[0,0,0]]; 
_junk3=createSimpleObject["a3\props_f_exp\civilian\garbage\garbageheap_04_f.p3d",[0,0,0]]; 
_junk3=createSimpleObject["a3\props_f_exp\civilian\garbage\garbageheap_04_f.p3d",[0,0,0]]; 
_junk4=createSimpleObject["a3\structures_f\civ\garbage\garbage_square3_f.p3d",[0,0,0]]; 
_junk5=createSimpleObject["a3\structures_f\civ\garbage\garbage_square5_f.p3d",[0,0,0]]; 
_junk6=createSimpleObject["a3\structures_f\civ\garbage\garbage_line_f.p3d",[0,0,0]]; 
_rack=createSimpleObject["a3\Structures_F_Enoch\Furniture\School_equipment\class_case_a_open.p3d",[0,0,0]]; 
_rack2=createSimpleObject["A3\Structures_F\Furniture\Metal_rack_F.p3d",[0,0,0]];
_sofa=createSimpleObject["a3\props_f_orange\furniture\sofa_01_f.p3d",[0,0,0]];
_sofa2=createSimpleObject["a3\props_f_orange\furniture\armchair_01_f.p3d",[0,0,0]];
_piano=createSimpleObject["a3\Structures_F_Enoch\Furniture\Decoration\piano\piano.p3d",[0,0,0]]; 
{_f pushBack _x}forEach[_book,_box,_box2,_chair,_chair2,_desk,_desk2,_junk,_junk2,_junk3,_junk4,_junk5,_junk6,_piano,_rack,_rack2,_sofa,_sofa2];_b setVariable["PF",_f];
_book setPos(_b modelToWorld[2,-1.3,-2.23]);
_box setPos(_b modelToWorld[2.17,2.1,-1.8]);_box setDir(_dir+95);
_box2 setPos(_b modelToWorld[2.23,3,-1.8]);_box2 setDir(_dir+80);
_chair setPos(_b modelToWorld[3.7,6,-5.5]);
_chair2 setPos(_b modelToWorld[0.5,-5.2,-0.89]);_chair2 setDir(_dir+210);
_desk setPos(_b modelToWorld[0.5,-4.5,-1.52]);
_desk2 setPos(_b modelToWorld[-0.2,-7.2,-1.29]);
_junk setPos(_b modelToWorld[-5.37,3,-4.5]);
_junk2 setPos(_b modelToWorld[-4.1,5.6,-1.25]);
_junk3 setPos(_b modelToWorld[-3.8,-2.02,-4.475]);_junk3 setDir(_dir+270);
_junk4 setPos(_b modelToWorld[-2.9,0.5,-5.391]);
_junk5 setPos(_b modelToWorld[-2.2,1.3,-5.416]);
_junk6 setPos(_b modelToWorld[-4.4,5.15,-5.394]);_junk6 setDir(_dir+90);
_piano setPos(_b modelToWorld[2,0.3,-4.6]);_piano setDir(_dir+150); 
_rack setPos(_b modelToWorld[2.5,5.97,-5.5]); 
_rack2 setPos(_b modelToWorld[0.35,7.8,-3.68]);
_sofa setPos(_b modelToWorld[-2.34,-4,-1.24]);_sofa setDir(_dir+90);
_sofa2 setPos(_b modelToWorld[-2,-1.9,-1.26]);_sofa2 setDir(_dir+130);
{_x setDir _dir}forEach[_chair,_junk,_junk2,_junk4,_junk5,_rack,_rack2];
{_x setDir(_dir+180)}forEach[_book,_desk,_desk2]}
