//Land_i_House_Small_02_V1_F
isNil{params["_b"];
if(isNil{_b getVariable"PF_B"})then{_b setVariable["PF_B","h2c_1"]};_f=[];_dir=getDir _b;
_bed=createSimpleObject["a3\structures_f\civ\Camping\CampingTable_F.p3d",[0,0,0]];
_blanky=createSimpleObject[(selectRandom["A3\Structures_F\Civ\Camping\Sleeping_bag_F.p3d","A3\Structures_F\Civ\Camping\Sleeping_bag_blue_F.p3d","A3\Structures_F\Civ\Camping\Sleeping_bag_brown_F.p3d"]),[0,0,0]];
_chair=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_chair2=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_chair3=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_desk=createSimpleObject["a3\structures_f\furniture\TableDesk_F.p3d",[0,0,0]];
_desk2=createSimpleObject["a3\structures_f\furniture\TableDesk_F.p3d",[0,0,0]];
_desk3=createSimpleObject["a3\structures_f\furniture\TableDesk_F.p3d",[0,0,0]];
_fridge=createSimpleObject["Fridge_01_closed_F",[0,0,0]];
_mw=createSimpleObject["A3\Structures_F_Heli\Items\Electronics\Microwave_01_F.p3d",[0,0,0]];
_pilo=createSimpleObject[(selectRandom["Land_pilo_F","Land_pilo_camouflage_F","Land_pilo_grey_F","Land_pilo_old_F"]),[0,0,0]];
_plant=createSimpleObject["a3\Props_F_Orange\Items\Decorative\FlowerPot_01_flower_F.p3d",[0,0,0]];
_rack=createSimpleObject["A3\Structures_F_Heli\Furniture\OfficeCabinet_01_F.p3d",[0,0,0]];
_sink=createSimpleObject["A3\Structures_F\Civ\Accessories\Sink_F.p3d",[0,0,0]];
_sofa=createSimpleObject["a3\Props_F_Orange\Furniture\Armchair_01_F.p3d",[0,0,0]];
_sofa2=createSimpleObject["a3\Props_F_Orange\Furniture\Sofa_01_F.p3d",[0,0,0]];
_table=createSimpleObject["A3\Structures_F_Heli\Furniture\RattanTable_01_F.p3d",[0,0,0]];
_table2=createSimpleObject["a3\Props_F_Orange\Furniture\TableSmall_01_F.p3d",[0,0,0]];
_table3=createSimpleObject["a3\Props_F_Orange\Furniture\TableBig_01_F.p3d",[0,0,0]];
_tv=createSimpleObject["Land_FlatTV_01_F",[0,0,0]];
{_f pushBack _x}forEach[_bed,_blanky,_chair,_chair2,_chair3,_desk,_desk2,_desk3,_fridge,_mw,_pilo,_plant,_rack,_sink,_sofa,_sofa2,_table,_table2,_table3,_tv];
_b setVariable["PF",_f];

_bed setPos(_b modelToWorld[6.6,2.5,-.295]);_bed setDir(_dir+180);
_blanky setPos(_b modelToWorld[6.6,2.55,-.26]);
_chair setPos(_b modelToWorld[1.5,-1.89,-.75]);_chair setDir(_dir+180);
_chair2 setPos(_b modelToWorld[1.86,-1.3,-.75]);
_chair3 setPos(_b modelToWorld[1.86,-.5,-.75]);
_desk setPos(_b modelToWorld[.38,-2.8,-.04]);
_desk2 setPos(_b modelToWorld[.38,-1.24,-.04]);
_desk3 setPos(_b modelToWorld[.34,-1.5,-.041]);_desk3 setDir(_dir+270);
_fridge setPos(_b modelToWorld[.38,-.04,.27]);
_mw setPos(_b modelToWorld[.4,-2,.14]);
_pilo setPos(_b modelToWorld[7.3,2.5,-.2]);
_plant setPos(_b modelToWorld[7.1,-2.5,1.645]);_plant setDir(random 359);
_rack setPos(_b modelToWorld[3.5,2.67,.82]);
_sink setPos(_b modelToWorld[-1.1,-3,.49]);
_sofa setPos(_b modelToWorld[7.03,-1.5,.20]);_sofa setDir(_dir+270);
_sofa2 setPos(_b modelToWorld[5.5,-2.85,.25]);
_table setPos(_b modelToWorld[7.15,-2.6,.05]);
_table2 setPos(_b modelToWorld[5,-.5,-.311]);
_table3 setPos(_b modelToWorld[1.56,-1,.15]);
_tv setPos(_b modelToWorld[5,-.5,.31]);_tv setDir(_dir-25);
{_x setDir _dir}forEach[_pilo,_rack,_sink,_sofa2,_table];
{_x setDir(_dir+90)}forEach[_blanky,_chair2,_chair3,_desk,_desk2,_fridge,_mw,_table2,_table3];
if((dayTime<18)&&{(dayTime>5)})then{_tv setObjectTextureGlobal[0,(selectRandom["A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_pills_co.paa","A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_supermarket_co.paa","A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_maskrtnik_co.paa","\A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_bluking_co.paa","\A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_wine_co.paa","A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_plane_co.paa","A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_action_co.paa","A3\Structures_F_Argo\Commercial\Billboards\Data\Advertisements\bill_getlost_co.paa"])]}}