//Land_CarService_F
isNil{params["_b"];_f=[];_dir=getDir _b;
_bucket1=createSimpleObject["A3\Props_F_Orange\Humanitarian\Supplies\PlasticBucket_01_F.p3d",[0,0,0]];
_bucket2=createSimpleObject["A3\Props_F_Orange\Humanitarian\Supplies\PlasticBucket_01_F.p3d",[0,0,0]];
_can=createSimpleObject["A3\Structures_F\Items\Vessels\CanisterPlastic_F.p3d",[0,0,0]];
_car=createSimpleObject["A3\soft_f_gamma\Hatchback_01\Hatchback_01_F.p3d",[0,0,0]];
_cart1=createSimpleObject["A3\Structures_F_Heli\Civ\Constructions\ToolTrolley_02_F.p3d",[0,0,0]];
_cart2=createSimpleObject["A3\Structures_F_Heli\Civ\Constructions\ToolTrolley_01_F.p3d",[0,0,0]];
_cart3=createSimpleObject["A3\Structures_F_Heli\Civ\Constructions\WeldingTrolley_01_F.p3d",[0,0,0]];
_chair1=createSimpleObject["a3\structures_f\civ\Camping\CampingChair_V2_F.p3d",[0,0,0]];
_chair2=createSimpleObject["a3\structures_f\civ\Camping\CampingChair_V2_F.p3d",[0,0,0]];
_chair3=createSimpleObject["A3\Structures_F_Heli\Furniture\OfficeChair_01_F.p3d",[0,0,0]];
_crates=createSimpleObject["A3\Structures_F\Civ\Market\CratesWooden_F.p3d",[0,0,0]];
_desk=createSimpleObject["a3\structures_f\furniture\TableDesk_F.p3d",[0,0,0]];
_drill=createSimpleObject["A3\Structures_F\Items\Tools\DrillAku_F.p3d",[0,0,0]];
_file=createSimpleObject["A3\Structures_F\Items\Tools\File_F.p3d",[0,0,0]];
_glove=createSimpleObject["a3\Props_F_Orange\Humanitarian\Garbage\MedicalGarbage_01_Gloves_F.p3d",[0,0,0]];
_grinder=createSimpleObject["A3\Structures_F\Items\Tools\Grinder_F.p3d",[0,0,0]];
_sign=createSimpleObject["A3\Structures_F_Argo\Commercial\Billboards\Billboard_02_carrental_F.p3d",[0,0,0]];
_screwD1=createSimpleObject["A3\Structures_F\Items\Tools\Screwdriver_V2_F.p3d",[0,0,0]];
_screwD2=createSimpleObject["A3\Structures_F\Items\Tools\Screwdriver_V1_F.p3d",[0,0,0]];
_plant=createSimpleObject["a3\Props_F_Orange\Items\Decorative\FlowerPot_01_flower_F.p3d",[0,0,0]];
_spray=createSimpleObject["A3\Structures_F_EPA\Items\Medical\DisinfectantSpray_F.p3d",[0,0,0]];
_tape1=createSimpleObject["A3\Structures_F_EPA\Items\Tools\DuctTape_F.p3d",[0,0,0]];
_tape2=createSimpleObject["A3\Structures_F_EPA\Items\Tools\DuctTape_F.p3d",[0,0,0]];
_tires=createSimpleObject["A3\Structures_F_Bootcamp\Civ\SportsGrounds\TyreBarrier_01_black_F.p3d",[0,0,0]];
_trash=createSimpleObject["A3\Structures_F_Heli\Civ\Garbage\WheelieBin_01_F.p3d",[0,0,0]];
_wTank=createSimpleObject["A3\Structures_F_Heli\Civ\Constructions\GasTank_02_F.p3d",[0,0,0]];
{_f pushBack _x}forEach[_bucket1,_bucket2,_can,_car,_cart1,_cart2,_cart3,_chair1,_chair2,_chair3,_crates,_desk,_drill,_file,_glove,_grinder,_sign,_screwD1,_screwD2,_plant,_spray,_tape1,_tape2,_tires,_trash,_wTank];
_b setVariable["PF",_f];

_bucket1 setPos(_b modelToWorld[-5.1,0,-.84]);_bucket1 setDir(_dir+295);
_bucket2 setPos(_b modelToWorld[-5.18,0.37,-.84]);
_can setPos(_b modelToWorld[-5.1,5.85,-.635]);
_car setPos(_b modelToWorld[-2.73,3.5,1.67]);{_car hideSelection[_x,true]}forEach["clan","daylights","light_l","light_r","reverse_light","zadni svetlo","brzdove svetlo"];
_cart1 setPos(_b modelToWorld[-5.1,8,-.33]);
_cart2 setPos(_b modelToWorld[-5,6.8,-.3]);
_cart3 setPos(_b modelToWorld[-2.5,7,.11]);_cart3 setDir(_dir+120);
_chair1 setPos(_b modelToWorld[4.67,-0.5,-.28]);_chair1 setDir(_dir+95);
_chair2 setPos(_b modelToWorld[4.6,0.5,-.28]);_chair2 setDir(_dir+88);
_chair3 setPos(_b modelToWorld[0.6,3,.06]);_chair3 setDir(_dir+320);
_crates setPos(_b modelToWorld[1.3,7.82,.2]);
_desk setPos(_b modelToWorld[0.94,1.7,-.46]);
_drill setPos(_b modelToWorld[-5.15,7.2,-.25]);_drill setVectorUp[-1,0,0];
_trash setPos(_b modelToWorld[4.6,8.1,-.26]);
_sign setPos(_b modelToWorld[3.9,-2.1,1.5]);
_glove setPos(_b modelToWorld[-2.5,5.15,.06]);
_tape1 setPos(_b modelToWorld[-2.65,5.2,.066]);
_tape2 setPos(_b modelToWorld[-2.33,1.7,.525]);_tape2 setDir 90;_tape2 setVectorUp[-0.07,0.02,-.4];
_tires setPos(_b modelToWorld[-5.05,-1.4,-.63]);
_screwD1 setPos(_b modelToWorld[-4.9,6.5,-.4]);_screwD1 setDir(_dir+40);
_screwD2 setPos(_b modelToWorld[-5,6.6,-.4]);
_file setPos(_b modelToWorld[-5,6.9,-.4]);_file setDir(_dir+280);
_spray setPos(_b modelToWorld[-2.33,1.9,.77]);_spray setDir(_dir+50);
_grinder setPos(_b modelToWorld[-5.1,8,-.18]);_grinder setDir(_dir+295);
_plant setPos(_b modelToWorld[4.6,-1.4,.32]);
_wTank setPos(_b modelToWorld[-0.4,-1.5,.43]);_wTank setDir(_dir+120);
{_x setDir _dir}forEach[_bucket2,_can,_desk,_sign,_tires,_screwD2,_plant,_tape1];
{_x setDir(_dir+180)}forEach[_car,_cart1,_cart2,_crates,_glove,_trash];
{_x setVectorUp[0,0.002,0.01]}forEach[_glove,_tape1]}