//Land_i_House_Small_03_V1_F
isNil{params["_b"];_f=[];_dir=getDir _b;
_bed1=createSimpleObject["a3\structures_f\civ\Camping\CampingTable_F.p3d",[0,0,0]];
_bed2=createSimpleObject["a3\structures_f\civ\Camping\CampingTable_F.p3d",[0,0,0]];
_blanket=[(selectRandom["A3\Structures_F\Civ\Camping\Sleeping_bag_F.p3d","A3\Structures_F\Civ\Camping\Sleeping_bag_blue_F.p3d","A3\Structures_F\Civ\Camping\Sleeping_bag_brown_F.p3d"]),[0,0,0]];
_blanket1=createSimpleObject _blanket;
_blanket2=createSimpleObject _blanket;
_chair1=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_chair2=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_chair3=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_chair4=createSimpleObject["a3\structures_f\furniture\ChairWood_F.p3d",[0,0,0]];
_desk1=createSimpleObject["a3\structures_f\furniture\TableDesk_F.p3d",[0,0,0]];
_desk2=createSimpleObject["a3\structures_f\furniture\TableDesk_F.p3d",[0,0,0]];
_desk3=createSimpleObject["OfficeTable_01_old_F",[0,0,0]];
_dTable=createSimpleObject["a3\Props_F_Orange\Furniture\TableBig_01_F.p3d",[0,0,0]];
_fridge=createSimpleObject["Fridge_01_closed_F",[0,0,0]];
_microW=createSimpleObject["A3\Structures_F_Heli\Items\Electronics\Microwave_01_F.p3d",[0,0,0]];
_pcCase=createSimpleObject["A3\Structures_F_Heli\Items\Electronics\PCSet_01_case_F.p3d",[0,0,0]];
_pcKey=createSimpleObject["A3\Structures_F_Heli\Items\Electronics\PCSet_01_keyboard_F.p3d",[0,0,0]];
_pcM=createSimpleObject["A3\Structures_F_Heli\Items\Electronics\PCSet_01_mouse_F.p3d",[0,0,0]];
_pcMon=createSimpleObject["A3\Structures_F_Heli\Items\Electronics\PCSet_01_screen_F.p3d",[0,0,0]];
_pillow=selectRandom["Land_Pillow_F","Land_Pillow_camouflage_F","Land_Pillow_grey_F","Land_Pillow_old_F"];
_pillow1=createSimpleObject[_pillow,[0,0,0]];
_pillow2=createSimpleObject[_pillow,[0,0,0]];
_plant=createSimpleObject["a3\Props_F_Orange\Items\Decorative\FlowerPot_01_flower_F.p3d",[0,0,0]];
_rack1=createSimpleObject["a3\structures_f\furniture\Rack_F.p3d",[0,0,0]];
_rack2=createSimpleObject["A3\Structures_F_Heli\Furniture\OfficeCabinet_01_F.p3d",[0,0,0]];
_sink=createSimpleObject["A3\Structures_F\Civ\Accessories\Sink_F.p3d",[0,0,0]];
_sofa=createSimpleObject["a3\Props_F_Orange\Furniture\Armchair_01_F.p3d",[0,0,0]];
_sTable=createSimpleObject["A3\Structures_F_Heli\Furniture\RattanTable_01_F.p3d",[0,0,0]];
{_f pushBack _x}forEach[_bed1,_bed2,_blanket1,_blanket2,_chair1,_chair2,_chair3,_chair4,_desk1,_desk2,_desk3,_dTable,_fridge,_microW,_pcCase,_pcKey,_pcM,_pcMon,_pillow1,_pillow2,_plant,_rack1,_rack2,_sink,_sofa,_sTable];
_b setVariable["PF",_f];

_bed1 setPos(_b modelToWorld[-5.07,3.9,.46]);
_bed2 setPos(_b modelToWorld[-4.35,3.9,.46]);
_blanket1 setPos(_b modelToWorld[-5.07,3.9,.495]);
_blanket2 setPos(_b modelToWorld[-4.35,3.9,.495]);
_chair1 setPos(_b modelToWorld[3,-5.3,-.01]);_chair1 setDir(_dir-20);
_chair2 setPos(_b modelToWorld[3.8,-5.3,-.01]);_chair2 setDir(_dir+5);
_chair3 setPos(_b modelToWorld[4.5,-5.3,-.01]);_chair3 setDir(_dir+30);
_chair4 setPos(_b modelToWorld[.75,1.4,-.01]);
_desk1 setPos(_b modelToWorld[5.1,1.627,.7]);
_desk2 setPos(_b modelToWorld[5.1,-2.229,.7]);
_desk3 setPos(_b modelToWorld[.5,1.15,0.83]);_desk3 setDir(_dir+180);
_dTable setPos(_b modelToWorld[3.8,-6,.88]);
_fridge setPos(_b modelToWorld[5.05,-3.44,1.02]);
_microW setPos(_b modelToWorld[5.1,-2,.88]);_microW setDir(_dir+(random 30+70));
_pcCase setPos(_b modelToWorld[1.4,1.2,.5]);_pcCase setDir(_dir+180);
_pcKey setPos(_b modelToWorld[.8,1.35,.83]);_pcKey setDir(_dir+175);
_pcM setPos(_b modelToWorld[.45,1.4,.862]);_pcM setDir(_dir+185);
_pcMon setPos(_b modelToWorld[.7,1,1.32]);_pcMon setDir(_dir+180);
_pillow1 setPos(_b modelToWorld[-4.35,4.6,.55]);
_pillow2 setPos(_b modelToWorld[-5.15,4.6,.55]);
_plant setPos(_b modelToWorld[-3.8,-1.9,2.376]);_plant setDir(random 259);
_rack1 setPos(_b modelToWorld[2.3,1.5,1.61]);
_rack2 setPos(_b modelToWorld[-2,-2.15,1.547]);_rack2 setDir(_dir+180);
_sink setPos(_b modelToWorld[5.1,-0.26,01.13]);
_sofa setPos(_b modelToWorld[-5,-1.80,.953]);
_sTable setPos(_b modelToWorld[-3.8,-1.9,.78]);
{_x setDir _dir}forEach[_blanket1,_blanket2,_chair4,_dTable,_pillow1,_pillow2,_rack1,_sofa,_sTable];
{_x setDir(_dir+90)}forEach[_bed1,_bed2,_desk1,_desk2,_fridge,_sink]}