//Land_Cargo_Patrol_V4_F
isNil{params["_b"];_f=[];_dir=getDir _b;
_table=createSimpleObject["a3\structures_f\civ\Camping\CampingTable_F.p3d",[0,0,0]];
_radio=createSimpleObject["A3\Structures_F\Items\Electronics\PortableLongRangeRadio_F.p3d",[0,0,0]];
_can=createSimpleObject["A3\Structures_F\Items\Food\Can_V3_F.p3d",[0,0,0]];
_shelf=createSimpleObject["A3\Structures_F_EPB\Furniture\ShelvesWooden_khaki_F.p3d",[0,0,0]];
_ammo0=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo1=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo2=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo3=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo4=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo5=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo6=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo7=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo8=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo9=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo10=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo11=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo12=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo13=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo14=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
_ammo15=createSimpleObject["A3\Structures_F_EPB\Items\Military\Ammobox_rounds_F.p3d",[0,0,0]];
 _hmg=createVehicle["B_HMG_01_high_F",[0,0,0],[],0,"can_collide"];
{_f pushBack _x}forEach[_ammo0,_ammo1,_ammo2,_ammo3,_ammo4,_ammo5,_ammo6,_ammo7,_ammo8,_ammo9,_ammo10,_ammo11,_ammo12,_ammo13,_ammo14,_ammo15,_can,_hmg,_radio,_shelf,_table];
_b setVariable["PF",_f];

_shelf setPos(_b modelToWorld[0,-2,.42]);_shelf setDir(_dir+90);
_ammo0 setPos(_b modelToWorld[.35,-2,.6]);_ammo0 setDir(_dir+90);
_ammo1 setPos(_b modelToWorld[.15,-2,.6]);
_ammo2 setPos(_b modelToWorld[-.05,-2,.6]);
_ammo3 setPos(_b modelToWorld[-.26,-2,.6]);
_ammo4 setPos(_b modelToWorld[-.38,-2,.26]);
_ammo5 setPos(_b modelToWorld[-.17,-2,.255]);
_ammo6 setPos(_b modelToWorld[.03,-2,.25]);
_ammo7 setPos(_b modelToWorld[.215,-2,.255]);
_ammo8 setPos(_b modelToWorld[.39,-2,.26]);
_ammo9 setPos(_b modelToWorld[.35,-2,-.06]);
_ammo10 setPos(_b modelToWorld[.13,-2,-.06]);_ammo10 setDir(_dir+85+(random 10));
_ammo11 setPos(_b modelToWorld[-.1,-2,-.06]);
_ammo12 setPos(_b modelToWorld[-.3,-2,-.06]);
_ammo13 setPos(_b modelToWorld[-0.2,-2,-.366]);
_ammo14 setPos(_b modelToWorld[0.05,-2,-.366]);
_ammo15 setPos(_b modelToWorld[0.3,-2,-.366]);
_table setPos(_b modelToWorld[1.7,-1.9,.24]);_table setDir _dir;
_radio setPos(_b modelToWorld[1.6,-1.9,.26]);_radio setDir(_dir+130+(random 60));
_can setPos(_b modelToWorld[2.3,-1.8,.31]);_can setDir(_dir+random 259);
_hmg setPos(_b modelToWorld[-1.75,-.85,-.62]);_hmg setDir(_dir+180);
{_x setDir(_dir+80+(random 15))}forEach[_ammo1,_ammo2,_ammo3,_ammo4,_ammo5,_ammo6,_ammo11,_ammo12];
{_x setDir(_dir+85+(random 5))}forEach[_ammo7,_ammo8,_ammo9];
{_x setDir(_dir+75+(random 25))}forEach[_ammo13,_ammo14,_ammo15]}